### ISSUE TITLE
Checkpoint is in Tensorflow (.ckpt) while the code is in Pytorch?

### ISSUE THREAD

**Issue by hongyanz** [yaircarmon/semisup-adv#1]
Nice work! I was checking the pretrained checkpoint in your repo. I find the checkpoint is in Tensorflow (.ckpt) while the evaluation code is in Pytorch. Is there an easy way to get .pt checkpoint file instead? Thanks.

**Comment by yaircarmon** [comment]
Thank you for your interest! Our checkpoints are in pytorch format and are readable using torch.load (see example in our code). Please let us know if you have any further questions or issues.
