### ISSUE TITLE
ImportError: Could not import FoolBox

### ISSUE THREAD

**Issue by momo1986** [yaircarmon/semisup-adv#4]
Thanks a lot for sharing.

I have problem in the procedure of evaluation.

> Traceback (most recent call last):
>   File "attack_evaluation.py", line 243, in <module>
>     eval_adv_test(model, device, test_loader, attack=args.attack,
>   File "attack_evaluation.py", line 85, in eval_adv_test
>     batch_linf_distances = cw(model, X, y,
>   File "/home/ubuntu/junyan/Python/adv_training/semisup-adv/attack_cw.py", line 32, in cw
>     raise ImportError('Could not import FoolBox')
> ImportError: Could not import FoolBox

Check the package import.

Failure for " from foolbox.attacks.base import call_decorator", " from foolbox.utils import onehot_like"import
My foolbox version is 3.3.1.

What is the specified foolbox version to run CW attack?
 Thanks & Regards!
Momo

**Comment by yaircarmon** [comment]
Hello,

Thanks for bringing the issue to our attention. As per the docstring in `attack_cw.py`, I believe that we worked with FoolBox 1.9. Please let me know if that version works for you and if it does I will update `environment.yml` accordingly.

Best,
Yair.

**Comment by momo1986** [comment]
Hello, @yaircarmon. 

I can run the evaluation procedure with the FoolBox version of 1.8.

Thanks a lot for your help!
Best Regards!
Momo
